language: python

python:
    - '3.6'
    - '3.7'
    - '3.8'

install: 
    - pip install -e ."[dev]"

script: 
    - flake8 linguist/*.py
    - flake8 test/*.py
    - pytest --cov=linguist

deploy:
    provider: pypi
    username: __token__
    password:
        secure: sQTq+tsHtG4KWvlUUwXhGHFvtVYYPPK/8h/ghorLEv3ZYiEOKat/hykt0WkJ5aew64PS0tWSavYwoSWbUMdOFxZcw8fiHZ/aSQByW9vDC90umQnBbQD6QU1AEPsEPXthMbukd691d1bXjlrmiZx7ARiiqEpaTdylgCAyj1bGa1cCodMcDeDLFAc+6qrLrA5lutvHV29aK31gmTCqzB39RCAcrXzOPelZ3AUfAcqUAiOoBxBxS0obraSy2411ARqKwUC249nCq16JtRixhGB5MeJtY25en1k23F47brJGv0ZWR+R4NV9uo2wy+CvCcwxh83+gEWjqejvyOVPI6+E2eyLggpptR5fsuC5TBd1nIfka2B18yNyYj8Zc5GSRhRrPo9Ob/XIZiunj4mLOaSAfWB7Ssw68lyj9G8k4aJUMVpy4x4cb7AQv8kWGSAC1I3mpAnydndytAiC+no0ujgLnweHEkJZaxfWsVKStaMXKggyZqNNWvA0/qVyesGH7wIbGdLZvB1BnIgIN2lNCuSrq7ylPOLRhX+BiIHrCThhB/nbtIhTWZ2Xq/jcyjRJkPB1fZj6jUtMzeXcm+vGMQnPvpgTowq6Dt0M3gQuBkxunL22guCKfSeplvAmYttFhpFsF8I0mZL736SA+W/hqNfwR3rC6EqCZsJ7sSRE6QGrkB6E=
    on:
        tags: true
    skip_existing: true

after_success:
    - coveralls
